# Generated by Django 5.2.15 on 2026-07-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trust_score',
            field=models.FloatField(default=0.5),
        ),
    ]
