# Generated by Django 5.2.15 on 2026-07-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, unique=True),
        ),
    ]
