# Generated by Django 5.2.15 on 2026-07-07 01:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('item_added', 'Item added'), ('item_updated', 'Item updated'), ('item_checked', 'Item checked'), ('item_removed', 'Item removed'), ('collaborator_joined', 'Collaborator joined'), ('collaborator_removed', 'Collaborator removed')], max_length=30)),
                ('detail', models.CharField(blank=True, default='', max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='lists.shoppinglist')),
            ],
            options={
                'verbose_name_plural': 'list activity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('view', 'View'), ('edit', 'Edit')], default='view', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='lists.shoppinglist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('list', 'user'), name='unique_list_collaborator')],
            },
        ),
    ]
