# Generated by Django 5.2.15 on 2026-07-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_listactivity_listcollaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='field_synced_at',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='listitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
