# Generated by Django 5.2.15 on 2026-07-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_listitem_field_synced_at_listitem_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listactivity',
            name='action',
            field=models.CharField(choices=[('item_added', 'Item added'), ('item_updated', 'Item updated'), ('item_checked', 'Item checked'), ('item_removed', 'Item removed'), ('collaborator_joined', 'Collaborator joined'), ('collaborator_removed', 'Collaborator removed'), ('list_scaled', 'List scaled')], max_length=30),
        ),
    ]
