# Generated by Django 5.2.15 on 2026-07-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_alter_listactivity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='event_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
