# Generated by Django 5.2.15 on 2026-07-07 02:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price_intelligence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('groceries', 'Groceries'), ('clothing', 'Clothing'), ('wishlist', 'Wishlist'), ('event', 'Event'), ('ingredients', 'Ingredients'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=280)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='price_intelligence.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='price_intelligence.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionOptOut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, choices=[('groceries', 'Groceries'), ('clothing', 'Clothing'), ('wishlist', 'Wishlist'), ('event', 'Event'), ('ingredients', 'Ingredients'), ('custom', 'Custom')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opt_outs', to='price_intelligence.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_opt_outs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('store__isnull', False), ('category', '')), models.Q(('store__isnull', True), models.Q(('category', ''), _negated=True)), _connector='OR'), name='promotion_optout_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('store__isnull', False)), fields=('user', 'store'), name='unique_user_store_optout'), models.UniqueConstraint(condition=models.Q(('category', ''), _negated=True), fields=('user', 'category'), name='unique_user_category_optout')],
            },
        ),
    ]
