# Generated by Django 5.2.15 on 2026-07-22 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price_intelligence', '0002_gtin_verify'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GtinProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gtin', models.CharField(db_index=True, max_length=14, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=300)),
                ('brand', models.CharField(blank=True, default='', max_length=200)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('ingredients_text', models.TextField(blank=True, default='')),
                ('allergens', models.JSONField(blank=True, default=list)),
                ('traces', models.JSONField(blank=True, default=list)),
                ('nutriments', models.JSONField(blank=True, default=dict)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('nutriscore_grade', models.CharField(blank=True, default='', max_length=8)),
                ('quantity', models.CharField(blank=True, default='', max_length=80)),
                ('source', models.CharField(choices=[('off', 'Open Food Facts'), ('manual', 'Manual'), ('merged', 'Merged')], default='off', max_length=16)),
                ('region', models.CharField(default='ZA', max_length=8)),
                ('found', models.BooleanField(default=True)),
                ('raw_hash', models.CharField(blank=True, default='', max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shoppa_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gtin_products', to='price_intelligence.product')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gtin', models.CharField(db_index=True, max_length=14)),
                ('field', models.CharField(max_length=64)),
                ('suggested_value', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAllergenProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allergens', models.JSONField(blank=True, default=list)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allergen_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gtin', models.CharField(db_index=True, max_length=14)),
                ('level', models.CharField(blank=True, default='', max_length=16)),
                ('product_name', models.CharField(blank=True, default='', max_length=300)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['user', '-scanned_at'], name='product_ver_user_id_5809c0_idx')],
            },
        ),
    ]
